### ISSUE TITLE
Where is Data folder?

### ISSUE THREAD

**Issue by deepkshikha** [dkorobchenko-nv/tensorrt-demo#3]

**Comment by dkorobchenko** [comment]
Hi,

**If you are talking about the folder with the training data**, I've just updated the README about it:

The training is performed on the ImageNet dataset (ILSVRC2012, http://image-net.org). In particular, on the ImageNet subset "Tabby cat" and "Bernese mountain dog" (cats vs dogs).
You can change TRAIN_DATA_ROOT and TRAIN_LIST_FILE variables according to your localtion of the ImageNet dataset, or create a symlink /imagenet/ pointing to your location of the ImageNet.

**If you are talking about the output directory (where the "data/checkpoints/" folder will be located)**, then you should create and empty "data" forlder localy in the project root directory.
Then you need to go through all the steps (training, optimization, etc) and corresponding data files will be created in the data folder.
